version: '3'
services:
     redis-server:
       image: 'redisA'
       container_name: rediscontainer
     node-app:
      restart: always
      container_name: webcontainer
      build: .
      ports:
       - "4001:8081"
